# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phantom
email: youremailaddress@gmail.com
description: The Jekyll version of the Phantom theme by HTML5 UP.
url: http://www.silverstrandpt.com # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog

# Logo settings
logo-placeholder: images/logo.svg

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      categories: ""
      tags: []
      featured-image: ""
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      featured-image: ""
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      tags: []
      featured-image: ""
      homepage-thumbnail: ""
